version: '3'

services:

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-2.0.0
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "order:5:1,Kafka_Example:5:1"

  postgres:
    build: postgres
    environment:
      POSTGRES_PASSWORD: dbpass
      POSTGRES_USER: dbuser

  orderkafka:
    build: services/order-kafka
    links:
      - kafka
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  deliverykafka:
    build: services/delivery-kafka
    links:
      - kafka
      - postgres
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092


  eta:                # ETA Computation, on port 9070
    container_name: eta
    image: uberoo/eta-rpc
    ports:
      - "9070:8080"

  around:
      container_name: around
      image: uberoo/around-rpc
      ports:
        - "9110:8080"


  # Services for managing ORDER
  ordersfood:                      # service orders, on port 9080
    container_name: ordersfood
    image: uberoo/ordersfood-document
    depends_on:
      - database1
    ports:
      - "9080:8080"
    links:
      - database1


  database1:                       # MongoDB database : orders, on port 27017
    container_name: orders-database
    image: mongo:3.0
    volumes:
      - "./db/mongo_data1:/data/db"
    ports:
      - "27017:27017"


  # Services for managing FOOD
  foodService:                      # service resource, on port 9090
    container_name: food
    image: uberoo/food-rest
    depends_on:
    - foodDBService
    ports:
    - "9090:8080"

  foodDBService:                   # MongoDB database : resource, on port 27017
    container_name: food-database
    image: mongo:3.0
    volumes:
    - "./db/mongo_data2:/data/db"
    ports:
    - "27019:27017"

  food-db-init:                   # For preloading DB with some food items
    build: ./db
    links:
    - foodDBService



  # Services for managing DELIVERY
  delivery:                        # service delivery, on port 9100
    container_name: delivery
    image: uberoo/delivery-document
    depends_on:
          - database3
    ports:
      - "9100:8080"

  database3:                       # MongoDB database : catalogue, on port 27021
    container_name: delivery-database
    image: mongo:3.0
    volumes:
      - "./db/mongo_data3:/data/db"
    ports:
      - "27021:27017"



  # Services bank
  bank:
    container_name: bank
    image: uberoo/bank-document
    depends_on:
      - databasebank
    ports:
      - "9120:8080"

  databasebank:                       # MongoDB database : orders, on port 27017
    container_name: bank-database
    image: mongo:3.0
    volumes:
      - "./db/mongo_databank:/data/db"
    ports:
      - "27030:27017"

  feedback:                        # service feedback, on port 9130
    container_name: feedback
    image: uberoo/feedback-document
    depends_on:
      - feedback-database
    ports:
      - "9130:8080"

  feedback-database:                       # MongoDB database : on port 27023
    container_name: feedback-database
    image: mongo:3.0
    volumes:
      - "./db/mongo_feedbackdata:/data/db"
    ports:
      - "27031:27017"

  producer:
    container_name: producer
    image: ubero/producer






