version: '3'

services:

  eta:                # ETA Computation, on port 9070
    container_name: eta
    image: uberoo/eta-rpc
    ports:
      - "9070:8080"

  around:                # ETA Computation, on port 9070
      container_name: around
      image: uberoo/around-rpc
      ports:
        - "9110:8080"


  # Services for managing ORDER
  ordersfood:                      # service orders, on port 9080
    container_name: ordersfood
    image: uberoo/ordersfood-document
    depends_on:
      - database1
    ports:
      - "9080:8080"

  database1:                       # MongoDB database : orders, on port 27017
    container_name: orders-database
    image: mongo:3.0
    volumes:
      - "./mongo_data1:/data/db"
    ports:
      - "27017:27017"


  # Services for managing FOOD
  foodService:                      # service resource, on port 9090
    container_name: food
    image: uberoo/food-rest
    depends_on:
    - foodDBService
    ports:
    - "9090:8080"

  foodDBService:                   # MongoDB database : resource, on port 27017
    container_name: food-database
    image: mongo:3.0
    volumes:
    - "./mongo_data2:/data/db"
    ports:
    - "27019:27017"

  food-db-init:                   # For preloading DB with some food items
    build: ./db
    links:
    - foodDBService



  # Services for managing DELIVERY
  delivery:                        # service delivery, on port 9100
    container_name: delivery
    image: uberoo/delivery-document
    depends_on:
          - database3
    ports:
      - "9100:8080"

  database3:                       # MongoDB database : catalogue, on port 27021
    container_name: delivery-database
    image: mongo:3.0
    volumes:
      - "./mongo_data3:/data/db"
    ports:
      - "27021:27017"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    links:
      - zookeeper:zk
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_CREATE_TOPICS: "topic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: "zk:2181"
    healthcheck:
      test: "kafka-topics.sh --zookeeper zookeeper:2181 --list 2>&1 | grep \"topic\""